### ddos part-correlation
#### 1.导入数据
#### 2.特征预处理
#### 3.数据相关性-皮尔逊相关系数
#### 4.比较平衡和非平衡数据集
#### 5.去除相关性较大的特征

In [9]:
import ipynb_importer

In [10]:
!ls /work/datasets/

ddos_balanced.7z    train_triplets.txt.zip
ddos_imbalanced.7z  unbalaced_20_80_dataset.csv
final_dataset.csv   unbalaced_test.csv
fin.csv		    yelp_academic_dataset_business.json.zip


In [11]:
import numpy as np
import pandas as pd


def get_orgrin_data(file_path):
    return pd.read_csv(file_path, low_memory=False)


def get_data_set(file_path):

    ddos_data = pd.read_csv(file_path, low_memory=False)
    # 暂时剔除无意义的特征
    del ddos_data['Row']
    # 删除非数值列
    other_data = ddos_data.drop([
        'Flow ID', 'Src IP', 'Src Port', 'Dst IP', 'Dst Port', 'Protocol',
        'Timestamp'
    ],
                                axis=1)
    # 删除空值
    other_data = other_data.dropna(how='all')
    # 转换为numpy  aarray
    new_data = other_data.to_numpy()
    # 拆分特征列和目标列
    X, y = new_data[:, :-1], new_data[:, -1]
    # 数值型转换类型
    X = X.astype(float)
    # 处理nan or inf
    X = np.nan_to_num(X)
    return X, y

In [62]:
file_path="/work/datasets/unbalaced_test.csv"
ddos_data = get_orgrin_data(file_path)
ddos_data.head()

Row                                 Flow ID          Src IP  Src Port  \
0  1739476   172.31.69.25-18.219.193.20-80-37882-6   18.219.193.20   37882.0   
1  1822666      172.31.69.28-18.219.9.1-80-63287-6    172.31.69.28      80.0   
2   905739   172.31.69.28-52.14.136.135-80-63095-6   52.14.136.135   63095.0   
3  1143064  172.31.69.28-18.216.200.189-80-52341-6  18.216.200.189   52341.0   
4  1934016   172.31.69.28-18.218.55.126-80-57459-6    172.31.69.28      80.0   

          Dst IP  Dst Port  Protocol               Timestamp  Flow Duration  \
0   172.31.69.25      80.0       6.0  16/02/2018 11:27:29 PM         8660.0   
1     18.219.9.1   63287.0       6.0  22/02/2018 12:13:52 AM         5829.0   
2   172.31.69.28      80.0       6.0  22/02/2018 12:14:02 AM         3396.0   
3   172.31.69.28      80.0       6.0  22/02/2018 12:28:04 AM         2390.0   
4  18.218.55.126   57459.0       6.0  22/02/2018 12:19:45 AM        17362.0   

   Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  TotLen Bwd Pkts  \
0           1.0           1.0              0.0              0.0   
1           4.0           3.0            935.0            298.0   
2           1.0           1.0              0.0              0.0   
3           1.0           1.0              0.0              0.0   
4           4.0           3.0            935.0            314.0   

   Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  Fwd Pkt Len Std  \
0              0.0              0.0              0.00              0.0   
1            935.0              0.0            233.75            467.5   
2              0.0              0.0              0.00              0.0   
3              0.0              0.0              0.00              0.0   
4            935.0              0.0            233.75            467.5   

   Bwd Pkt Len Max  Bwd Pkt Len Min  Bwd Pkt Len Mean  Bwd Pkt Len Std  \
0              0.0              0.0          0.000000         0.000000   
1            298.0              0.0         99.333333       172.050380   
2              0.0              0.0          0.000000         0.000000   
3              0.0              0.0          0.000000         0.000000   
4            314.0              0.0        104.666667       181.287985   

          Flow Byts/s         Flow Pkts/s  Flow IAT Mean  Flow IAT Std  \
0                 0.0  230.94688221709012    8660.000000      0.000000   
1  211528.56407617085  1200.8920912677988     971.500000   2104.124973   
2                 0.0   588.9281507656066    3396.000000      0.000000   
3                 0.0   836.8200836820082    2390.000000      0.000000   
4   71938.71673770303  403.17935721691055    2893.666667   6770.577661   

   Flow IAT Max  Flow IAT Min  Fwd IAT Tot  Fwd IAT Mean  Fwd IAT Std  \
0        8660.0        8660.0          0.0      0.000000     0.000000   
1        5260.0           7.0       5822.0   1940.666667  3119.411857   
2        3396.0        3396.0          0.0      0.000000     0.000000   
3        2390.0        2390.0          0.0      0.000000     0.000000   
4       16711.0           7.0      17355.0   5785.000000  9779.680414   

   Fwd IAT Max  Fwd IAT Min  Bwd IAT Tot  Bwd IAT Mean   Bwd IAT Std  \
0          0.0          0.0          0.0           0.0      0.000000   
1       5541.0         46.0       5540.0        2770.0   3521.391770   
2          0.0          0.0          0.0           0.0      0.000000   
3          0.0          0.0          0.0           0.0      0.000000   
4      17077.0         38.0      17074.0        8537.0  11559.781659   

   Bwd IAT Max  Bwd IAT Min  Fwd PSH Flags  Bwd PSH Flags  Fwd URG Flags  \
0          0.0          0.0            0.0            0.0            0.0   
1       5260.0        280.0            0.0            0.0            0.0   
2          0.0          0.0            0.0            0.0            0.0   
3          0.0          0.0            0.0            0.0            0.0   
4      16711.0        363.0            0.0            0.0    

In [18]:
ddos_data["Label"]=ddos_data["Label"].map({"Benign":0,"ddos":1})
ddos_data

Row                                  Flow ID          Src IP  \
0       1739476    172.31.69.25-18.219.193.20-80-37882-6   18.219.193.20   
1       1822666       172.31.69.28-18.219.9.1-80-63287-6    172.31.69.28   
2        905739    172.31.69.28-52.14.136.135-80-63095-6   52.14.136.135   
3       1143064   172.31.69.28-18.216.200.189-80-52341-6  18.216.200.189   
4       1934016    172.31.69.28-18.218.55.126-80-57459-6    172.31.69.28   
...         ...                                      ...             ...   
100005  1725894   172.31.67.50-209.85.203.113-53598-80-6  209.85.203.113   
100006  5681778   172.31.69.17-108.174.10.14-54599-443-6    172.31.69.17   
100007  6395326      172.31.0.2-172.31.65.49-53-61087-17    172.31.65.49   
100008  4926899      172.31.0.2-172.31.67.58-53-61580-17    172.31.67.58   
100009  7656685  169.254.169.254-172.31.65.89-80-49393-6    172.31.65.89   

        Src Port           Dst IP  Dst Port  Protocol               Timestamp  \
0        37882.0     172.31.69.25      80.0       6.0  16/02/2018 11:27:29 PM   
1           80.0       18.219.9.1   63287.0       6.0  22/02/2018 12:13:52 AM   
2        63095.0     172.31.69.28      80.0       6.0  22/02/2018 12:14:02 AM   
3        52341.0     172.31.69.28      80.0       6.0  22/02/2018 12:28:04 AM   
4           80.0    18.218.55.126   57459.0       6.0  22/02/2018 12:19:45 AM   
...          ...              ...       ...       ...                     ...   
100005      80.0     172.31.67.50   53598.0       6.0     20/02/2018 05:14:52   
100006   54599.0    108.174.10.14     443.0       6.0     20/02/2018 03:08:35   
100007   61087.0       172.31.0.2      53.0      17.0     20/02/2018 01:03:19   
100008   61580.0       172.31.0.2      53.0      17.0     20/02/2018 12:43:11   
100009   49393.0  169.254.169.254      80.0       6.0     20/02/2018 09:55:40   

        Flow Duration  Tot Fwd Pkts  ...  Fwd Seg Size Min  Active Mean  \
0              8660.0           1.0  ...               0.0          0.0   
1              5829.0           4.0  ...               0.0          0.0   
2              3396.0           1.0  ...               0.0          0.0   
3              2390.0           1.0  ...               0.0          0.0   
4             17362.0           4.0  ...               0.0          0.0   
...               ...           ...  ...               ...          ...   
100005           50.0           1.0  ...              20.0          0.0   
100006          306.0           3.0  ...              20.0          0.0   
100007          362.0           1.0  ...               8.0          0.0   
100008          303.0           1.0  ...               8.0          0.0   
100009           54.0           2.0  ...              20.0          0.0   

        Active Std  Active Max  Active Min  Idle Mean  Idle Std  Idle Max  \
0              0.0         0.0         0.0        0.0       0.0       0.0   
1              0.0         0.0         0.0        0.0       0.0       0.0   
2              0.0         0.0         0.0        0.0       0.0       0.0   
3              0.0         0.0         0.0        0.0       0.0       0.0   
4              0.0         0.0         0.0        0.0       0.0       0.0   
...            ...         ...         ...        ...       ...       ...   
100005         0.0         0.0         0.0        0.0       0.0       0.0   
100006         0.0         0.0         0.0        0.0       0.0       0.0   
100007         0.0         0.0         0.0        0.0       0.0       0.0   
100008         0.0         0.0         0.0        0.0       0.0       0.0   
100009         0.0         0.0         0.0        0.0       0.0       0.0   

        Idle Min  Label  
0            0.0    1.0  
1            0.0    1.0  
2            0.0    1.0  
3            0.0    1.0  
4            0.0    1.0  
...          ...    ...  
100005       0.0    0.0  
100006       0.0    0.0  
100007       0.0    0.0  
100008       0.0    0.0  
100009       0

In [20]:
corr_matrix=ddos_data.corr()

Label               1.000000
ACK Flag Cnt        0.423072
Fwd Pkt Len Std     0.269671
Dst Port            0.210095
Fwd Seg Size Avg    0.204897
                      ...   
Fwd Pkts/b Avg           NaN
Fwd Blk Rate Avg         NaN
Bwd Byts/b Avg           NaN
Bwd Pkts/b Avg           NaN
Bwd Blk Rate Avg         NaN
Name: Label, Length: 78, dtype: float64

In [22]:
pd.set_option('display.max_rows',100)      #设置最大行数
pd.set_option('display.max_columns', 100)  #设置最大列数
# 皮尔逊相关系数矩阵 ，只计算数值类型
label_corr=corr_matrix["Label"].sort_values(ascending=False)

Label                1.000000
ACK Flag Cnt         0.423072
Fwd Pkt Len Std      0.269671
Dst Port             0.210095
Fwd Seg Size Avg     0.204897
Fwd Pkt Len Mean     0.204897
Fwd Pkt Len Max      0.202123
CWE Flag Count       0.196849
Down/Up Ratio        0.156982
SYN Flag Cnt         0.130454
Pkt Len Std          0.100324
Pkt Len Var          0.059971
Pkt Len Max          0.059157
ECE Flag Cnt         0.034061
Bwd Pkts/s           0.028494
Init Bwd Win Byts    0.010451
Subflow Fwd Byts     0.008577
TotLen Fwd Pkts      0.008577
Fwd Act Data Pkts    0.008119
Tot Fwd Pkts         0.007819
Subflow Fwd Pkts     0.007819
Fwd Header Len       0.007591
FIN Flag Cnt         0.005962
Bwd IAT Std         -0.020736
Bwd Header Len      -0.022382
TotLen Bwd Pkts     -0.022731
Subflow Bwd Byts    -0.022731
Tot Bwd Pkts        -0.031383
Subflow Bwd Pkts    -0.031383
Flow IAT Min        -0.040002
Bwd PSH Flags       -0.043300
Fwd IAT Min         -0.047873
Pkt Len Mean        -0.051278
Active Min

In [34]:
np.abs(corr_matrix["Label"].values)<=0.03

/work/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in less_equal
  """Entry point for launching an IPython kernel.


array([False, False, False, False,  True, False,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False,  True,  True,
       False,  True, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
       False,  True, False,  True,  True, False, False, False, False,
       False, False, False, False, False, False])

In [ ]:
Subflow Fwd Byts     0.008577
TotLen Fwd Pkts      0.008577
Fwd Act Data Pkts    0.008119
Tot Fwd Pkts         0.007819
Subflow Fwd Pkts     0.007819
Fwd Header Len       0.007591
FIN Flag Cnt         0.005962
Bwd IAT Std         -0.020736
Bwd Header Len      -0.022382
TotLen Bwd Pkts     -0.022731
Subflow Bwd Byts    -0.022731
Tot Bwd Pkts        -0.031383
Subflow Bwd Pkts    -0.031383
Flow IAT Min        -0.040002

In [36]:
ddos_14 = ddos_data[[
    "Subflow Fwd Byts", "TotLen Fwd Pkts", "Fwd Act Data Pkts", "Tot Fwd Pkts",
    "Subflow Fwd Pkts", "Fwd Header Len", "FIN Flag Cnt", "Bwd IAT Std",
    "Bwd Header Len", "TotLen Bwd Pkts", "Subflow Bwd Byts", "Tot Bwd Pkts",
    "Subflow Bwd Pkts", "Flow IAT Min"
]]
ddos_14.head()

Subflow Fwd Byts  TotLen Fwd Pkts  Fwd Act Data Pkts  Tot Fwd Pkts  \
0               0.0              0.0                0.0           1.0   
1             935.0            935.0                1.0           4.0   
2               0.0              0.0                0.0           1.0   
3               0.0              0.0                0.0           1.0   
4             935.0            935.0                1.0           4.0   

   Subflow Fwd Pkts  Fwd Header Len  FIN Flag Cnt   Bwd IAT Std  \
0               1.0            32.0           0.0      0.000000   
1               4.0            92.0           0.0   3521.391770   
2               1.0            20.0           0.0      0.000000   
3               1.0            20.0           0.0      0.000000   
4               4.0            92.0           0.0  11559.781659   

   Bwd Header Len  TotLen Bwd Pkts  Subflow Bwd Byts  Tot Bwd Pkts  \
0            32.0              0.0               0.0           1.0   
1            72.0            298.0             298.0           3.0   
2            20.0              0.0               0.0           1.0   
3            20.0              0.0               0.0           1.0   
4            72.0            314.0             314.0           3.0   

   Subflow Bwd Pkts  Flow IAT Min  
0               1.0        8660.0  
1               3.0           7.0  
2               1.0        3396.0  
3               1.0        2390.0  
4               3.0           7.0

In [87]:
ddos_data.columns

Index(['Row', 'Flow ID', 'Src IP', 'Src Port', 'Dst IP', 'Dst Port',
       'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count'

In [88]:
ddos_data.shape

(100010, 85)

In [37]:
X_14=ddos_14.to_numpy().astype(float)

In [46]:
X_14=np.nan_to_num(X_14)
X_14

array([[0.000e+00, 0.000e+00, 0.000e+00, ..., 1.000e+00, 1.000e+00,
        8.660e+03],
       [9.350e+02, 9.350e+02, 1.000e+00, ..., 3.000e+00, 3.000e+00,
        7.000e+00],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 1.000e+00, 1.000e+00,
        3.396e+03],
       ...,
       [4.500e+01, 4.500e+01, 0.000e+00, ..., 1.000e+00, 1.000e+00,
        3.620e+02],
       [4.700e+01, 4.700e+01, 0.000e+00, ..., 1.000e+00, 1.000e+00,
        3.030e+02],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        5.400e+01]])

In [79]:
def label_encoder(y):
    # 标签数值化，方便处理
    from sklearn.preprocessing import LabelEncoder
    le = LabelEncoder()
    return le.fit_transform(y)

In [82]:
_, y = get_data_set(file_path)
y=label_encoder(y)
y

array([1, 1, 1, ..., 0, 0, 0])

In [93]:
y=np.hstack((y,1))

In [58]:
X_14.shape

(100010, 14)

In [94]:
#### 决策树验证一下准确率
from sklearn.model_selection import train_test_split
X_14_train, X_14_test, y_train, y_test = train_test_split(X_14,
                                                          y,
                                                          test_size=0.2,
                                                          random_state=2019)

In [95]:
%%time
from sklearn.tree import DecisionTreeClassifier
dt_tree = DecisionTreeClassifier()
dt_tree.fit(X_14_train, y_train)
y_pred = dt_tree.predict(X_14_test)
y_pred

CPU times: user 974 ms, sys: 0 ns, total: 974 ms
Wall time: 2.25 s


array([0, 1, 0, ..., 1, 1, 1])

In [96]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      3990
           1       1.00      1.00      1.00     16012

    accuracy                           0.99     20002
   macro avg       0.99      0.99      0.99     20002
weighted avg       0.99      0.99      0.99     20002



In [97]:
#### 继续减少特征,取相关性不大的10个特征做判别，准确率降低2-3百分点，尤其是召回率下降得比较快
# 通过增加以上特征，准确率将提高
ddos_10 = ddos_data[[
     "Fwd Act Data Pkts", "Tot Fwd Pkts",
    "Subflow Fwd Pkts", "Fwd Header Len", "FIN Flag Cnt", "Bwd IAT Std",
    "Bwd Header Len", "TotLen Bwd Pkts", "Subflow Bwd Byts", "Tot Bwd Pkts"
]]
ddos_10.head()

Fwd Act Data Pkts  Tot Fwd Pkts  Subflow Fwd Pkts  Fwd Header Len  \
0                0.0           1.0               1.0            32.0   
1                1.0           4.0               4.0            92.0   
2                0.0           1.0               1.0            20.0   
3                0.0           1.0               1.0            20.0   
4                1.0           4.0               4.0            92.0   

   FIN Flag Cnt   Bwd IAT Std  Bwd Header Len  TotLen Bwd Pkts  \
0           0.0      0.000000            32.0              0.0   
1           0.0   3521.391770            72.0            298.0   
2           0.0      0.000000            20.0              0.0   
3           0.0      0.000000            20.0              0.0   
4           0.0  11559.781659            72.0            314.0   

   Subflow Bwd Byts  Tot Bwd Pkts  
0               0.0           1.0  
1             298.0           3.0  
2               0.0           1.0  
3               0.0           1.0  
4             314.0           3.0

In [102]:
X_10=ddos_10.to_numpy()
X_10=np.nan_to_num(X_10)

In [103]:
from sklearn.model_selection import train_test_split
X_10_train, X_10_test, _, _ = train_test_split(X_10,
                                               y,
                                               test_size=0.2,
                                               random_state=2019)

In [104]:
%%time
from sklearn.tree import DecisionTreeClassifier
dt_tree = DecisionTreeClassifier()
dt_tree.fit(X_10_train, y_train)
y_pred = dt_tree.predict(X_10_test)
y_pred
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.83      0.90      3990
           1       0.96      1.00      0.98     16012

    accuracy                           0.96     20002
   macro avg       0.97      0.91      0.94     20002
weighted avg       0.97      0.96      0.96     20002

CPU times: user 0 ns, sys: 430 ms, total: 430 ms
Wall time: 907 ms
